enableInlineBuilds: true
enableGlobalCache: false
cacheFolder: ./node_modules/.yarn_cache
compressionLevel: 0
nodeLinker: pnp
enableTelemetry: false
defaultSemverRangePrefix: ""

packageExtensions:
  "eslint-plugin-react-x@*":
    dependencies:
      "ts-api-utils": "*"

yarnPath: .yarn/releases/yarn-4.9.3.cjs
